@TodoApi_HostAddress = https://localhost:44370

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems/3

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

PUT {{TodoApi_HostAddress}}/todoitems/3
Content-Type: application/json

{
  "name": "Have dinner",
  "isComplete": false
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/1

###

GET {{TodoApi_HostAddress}}/todoitems/

###
