@ApiCreadocs_HostAddress = https://localhost:44338

GET {{ApiCreadocs_HostAddress}}/api/interlocuteur

###

POST {{ApiCreadocs_HostAddress}}/api/interlocuteur
Content-Type: application/json

{
    "id_titre": 1,
    "id_agence": 3,
    "loginInter": "unnouveaulogin",
    "mdpInter": "lepasswordneuf",
    "loginKwInter": "l",
    "mdpKwInter": "l",
    "nomInter": "util4",
    "prenomInter": "deux",
    "telInter": "0123456789",
    "mailInter": "util@neuf.com"
}

###

GET {{ApiCreadocs_HostAddress}}/api/interlocuteur/2

###

DELETE {{ApiCreadocs_HostAddress}}/api/interlocuteur/7

###

POST {{ApiCreadocs_HostAddress}}/api/interlocuteur
Content-Type: application/json

{
    "mailInter": "m.soleri@unemail.com",
    "mdpInter": "unpassword",
    "nomInter": "SOLERI",
    "prenomInter": "Mathieu",
    "loginInter": "mSoleri"   
}

###

GET {{ApiCreadocs_HostAddress}}/api/agence

###

//Test de Login avec login et MDP valide
POST {{ApiCreadocs_HostAddress}}/api/interlocuteur/login
Content-Type: application/json

{
    "Email": "p.martin@agencecentrale.com",
    "Password": "password123" 
}

###

POST {{ApiCreadocs_HostAddress}}/api/interlocuteur/login
Content-Type: application/json

{
    "Email": "s.durand@agencenord.com",
    "Password": "password123" 
}

###
//Test de Login avec login et MDP erroné
POST {{ApiCreadocs_HostAddress}}/api/interlocuteur/login
Content-Type: application/json

{
    "Email": "s.drand@agrd.com",
    "Password": "pass23" 
}

###

POST {{ApiCreadocs_HostAddress}}/api/interlocuteur
Content-Type: application/json

{
    "id_titre": 1,
    "id_agence": 1,
    "loginInter": "UnePersonne",
    "mdpInter": "leMotDePasse",
    "loginKwInter": "l",
    "mdpKwInter": "K",
    "nomInter": "Mister",
    "prenomInter": "Mathieu",
    "telInter": "0123456789",
    "mailInter": "misterMat@uneadresse.com"
}

###

GET {{ApiCreadocs_HostAddress}}/api/sexe

###

GET {{ApiCreadocs_HostAddress}}/api/secu

###

POST {{ApiCreadocs_HostAddress}}/api/client
Content-Type: application/json

{
    "Client": {
        "id_sexe": "1",
        "id_ville": "0",
        "id_regimeSecu": null,
        "nomCli": "claude",
        "prenomCli": "claude",
        "numIdCli": "01456789568",
        "telCli": "01456789568",
        "mailCli": "jn.du@example.com",
        "depNaIssCli": null,
        "dateNaissCli": "1980-01-01",
        "add1Cli": "1 rue  la Paix",
        "add2Cli": null,
        "add3Cli": null,
        "numCompteCli": "FR71234546598765",
        "numSecuCli": "123456765490123"
    },
    "postalCode": "76001",
    "placeName": "guingamp",
    "countryCode": "FR",
    "countryName": "France"
}

###

POST {{ApiCreadocs_HostAddress}}/api/client
Content-Type: application/json

{
  "Client":
    {
      "id_sexe":"1",
      "id_ville":0,
      "id_regimeSecu":"1",
      "nomCli":"MEYRAN",
      "prenomCli":"Jean",
      "numIdCli":"654987369852dfgsdfg",
      "dateNaissCli":"1985-02-01",
      "depNaissCli":"66",
      "add1Cli":"La",
      "add2Cli":"Rue",
      "add3Cli":"LEPIC"
    },
  "postalCode":"75220",
  "placeName":"Paris 16",
  "countryCode":"FR",
  "countryName":"France"
}

###

    
    